CREATE INDEX new_arrivals_pending ON public.new_arrivals USING btree (last_seen) WHERE (processed_at IS NULL);
CREATE INDEX new_arrivals_domain ON public.new_arrivals USING btree (domain);
CREATE INDEX deal_revisions_deal_idx ON public.deal_revisions USING btree (deal_id, created_at DESC);
CREATE INDEX facet_counts_idx ON public.facet_counts USING btree (segment, key);
CREATE INDEX facet_coverage_idx ON public.facet_coverage USING btree (segment);
CREATE INDEX contacts_owner_idx ON public.contacts USING gin (owner);
CREATE INDEX contacts_countries_idx ON public.contacts USING gin (countries);
CREATE INDEX contacts_name_sort_idx ON public.contacts USING btree (segment, full_name, hr_id);
CREATE INDEX contacts_fts_idx ON public.contacts USING gin (to_tsvector('simple'::regconfig, ((((((COALESCE(full_name, ''::text) || ' '::text) || COALESCE(email, ''::text)) || ' '::text) || COALESCE(job_title, ''::text)) || ' '::text) || COALESCE(domain, ''::text))));
CREATE INDEX contact_emails_contact_idx ON public.contact_emails USING btree (contact_id);
CREATE INDEX contacts_segment_idx ON public.contacts USING btree (segment);
CREATE INDEX contacts_role_idx ON public.contacts USING btree (role);
CREATE INDEX contacts_account_idx ON public.contacts USING btree (account_id);
CREATE INDEX contacts_domain_idx ON public.contacts USING btree (domain);
CREATE INDEX contacts_status_idx ON public.contacts USING btree (best_email_status);
CREATE INDEX contacts_replied_idx ON public.contacts USING btree (replied) WHERE replied;
CREATE INDEX contacts_mailchimp_idx ON public.contacts USING btree (in_mailchimp) WHERE in_mailchimp;
CREATE INDEX contact_emails_trgm_idx ON public.contact_emails USING gin (email gin_trgm_ops);
CREATE INDEX accounts_segment_idx ON public.accounts USING btree (segment);
CREATE INDEX accounts_type_idx ON public.accounts USING btree (type);
CREATE INDEX accounts_domain_idx ON public.accounts USING btree (domain);
CREATE INDEX accounts_reachable_idx ON public.accounts USING btree (reachable_contact) WHERE reachable_contact;
CREATE INDEX accounts_included_idx ON public.accounts USING btree (included) WHERE included;
CREATE INDEX accounts_owner_idx ON public.accounts USING gin (owner);
CREATE INDEX accounts_countries_idx ON public.accounts USING gin (countries);
CREATE INDEX accounts_name_sort_idx ON public.accounts USING btree (segment, name, hr_id);
CREATE INDEX accounts_fts_idx ON public.accounts USING gin (to_tsvector('simple'::regconfig, ((((COALESCE(name, ''::text) || ' '::text) || COALESCE(domain, ''::text)) || ' '::text) || COALESCE(website, ''::text))));
CREATE INDEX inv_type_idx ON public.account_investor USING gin (investor_type);
CREATE INDEX inv_sector_idx ON public.account_investor USING gin (invests_in);
CREATE INDEX inv_countries_idx ON public.account_investor USING gin (invests_in_countries);
CREATE INDEX inv_via_idx ON public.account_investor USING gin (invests_via);
CREATE INDEX inv_aum_idx ON public.account_investor USING btree (aum_range);
CREATE INDEX inv_aum_amt_idx ON public.account_investor USING btree (aum_usd DESC NULLS LAST);
CREATE INDEX biz_industry_idx ON public.account_business USING gin (industry);
CREATE INDEX biz_projects_idx ON public.account_business USING gin (project_countries);
CREATE INDEX biz_stage_idx ON public.account_business USING btree (stage);
CREATE INDEX biz_ticker_idx ON public.account_business USING btree (ticker);
CREATE INDEX inter_type_idx ON public.account_intermediary USING btree (intermediary_type);
CREATE INDEX inter_sector_idx ON public.account_intermediary USING gin (sector_focus);
CREATE INDEX gov_kind_idx ON public.account_government USING btree (entity_kind);
CREATE INDEX gov_focus_idx ON public.account_government USING gin (mandate_focus);
CREATE INDEX mc_status_idx ON public.mailchimp_members USING btree (status);
CREATE INDEX mc_contact_idx ON public.mailchimp_members USING btree (contact_id);
CREATE INDEX mc_audiences_idx ON public.mailchimp_members USING gin (audiences);
CREATE INDEX deals_status_idx ON public.deals USING btree (status);
CREATE INDEX deals_company_idx ON public.deals USING btree (company_id);
CREATE INDEX deal_contacts_c_idx ON public.deal_contacts USING btree (contact_id);
CREATE INDEX deal_contacts_sent_idx ON public.deal_contacts USING btree (contact_id, sent_at DESC NULLS LAST);
CREATE INDEX contact_notes_c_idx ON public.contact_notes USING btree (contact_id, created_at DESC);
CREATE INDEX inv_invests_names_idx ON public.account_investor USING gin (invests_in_country_names);
CREATE INDEX biz_sector_split_idx ON public.account_business USING gin (sector);
CREATE INDEX biz_project_names_idx ON public.account_business USING gin (project_country_names);
CREATE INDEX accounts_country_names_idx ON public.accounts USING gin (country_names);
CREATE INDEX contacts_country_names_idx ON public.contacts USING gin (country_names);
CREATE INDEX inv_sector_split_idx ON public.account_investor USING gin (sector);
CREATE INDEX inv_commodity_idx ON public.account_investor USING gin (commodity);
CREATE INDEX inter_sector_split_idx ON public.account_intermediary USING gin (sector);
CREATE INDEX inter_commodity_idx ON public.account_intermediary USING gin (commodity);
CREATE INDEX biz_commodity_idx ON public.account_business USING gin (commodity);
CREATE INDEX contacts_search_trgm_idx ON public.contacts USING gin (search_text gin_trgm_ops);
CREATE INDEX accounts_search_trgm_idx ON public.accounts USING gin (search_text gin_trgm_ops);
CREATE INDEX deals_created_idx ON public.deals USING btree (created_at DESC);
CREATE INDEX deal_contacts_conv_idx ON public.deal_contacts USING btree (contact_id, conversation_id) WHERE (conversation_id IS NOT NULL);
CREATE INDEX mail_events_contact_idx ON public.mail_events USING btree (contact_id, occurred_at DESC);
CREATE INDEX mail_events_conv_idx ON public.mail_events USING btree (conversation_id) WHERE (conversation_id IS NOT NULL);
CREATE INDEX app_people_state_idx ON public.app_people USING btree (state, requested_at DESC);
CREATE INDEX access_tokens_person_idx ON public.access_tokens USING btree (person_id, purpose);
CREATE INDEX deal_drafts_deal_idx ON public.deal_drafts USING btree (deal_id, contact_id);
CREATE INDEX deal_drafts_conv_idx ON public.deal_drafts USING btree (conversation_id) WHERE (conversation_id IS NOT NULL);
CREATE INDEX deal_documents_deal_idx ON public.deal_documents USING btree (deal_id);
CREATE UNIQUE INDEX email_templates_name_idx ON public.email_templates USING btree (name);
CREATE INDEX contact_facet_counts_idx ON public.contact_facet_counts USING btree (segment, key);
CREATE INDEX contact_facet_coverage_idx ON public.contact_facet_coverage USING btree (segment);
CREATE INDEX deal_verdicts_account_idx ON public.deal_verdicts USING btree (account_id);
